# Generated by Django 4.2.1 on 2023-06-01 13:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('HighBP', models.BooleanField()),
                ('HighChol', models.BooleanField()),
                ('CholCheck', models.BooleanField()),
                ('BMI', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('Smoker', models.BooleanField()),
                ('Stroke', models.BooleanField()),
                ('Diabetes', models.IntegerField(choices=[(0, 'NO'), (1, 'Type 1'), (2, 'Type 2')])),
                ('PhysActivity', models.BooleanField()),
                ('Veggies', models.BooleanField()),
                ('NoDocbcCost', models.BooleanField()),
                ('GenHlth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('MentHlth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('PhysHlth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('DiffWalk', models.BooleanField()),
                ('Sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('Age', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('Income', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('result', models.BooleanField(null=True)),
                ('submitted_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
