# Generated by Django 4.2.1 on 2023-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMLtestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdisease',
            name='user_id',
            field=models.CharField(default=0),
        ),
    ]
