# Generated by Django 4.2.1 on 2023-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMLtestapp', '0002_alter_heartdisease_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdisease',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
